# Generated by Django 4.0.3 on 2022-06-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
