# Generated by Django 4.0.4 on 2022-06-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
