# Generated by Django 4.0.4 on 2022-09-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_tipos_elemento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
