# Generated by Django 4.0.3 on 2022-05-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_factura_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electrodomesticos',
            new_name='Electrodomestico',
        ),
    ]
