# Generated by Django 4.0.4 on 2022-05-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_remove_servicio_electrodomesticos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoelemento',
            name='producto',
        ),
        migrations.AddField(
            model_name='tipoelemento',
            name='nombre',
            field=models.CharField(choices=[('Accesorios', 'Accesorios'), ('Productos', 'Productos')], default='Productos', max_length=20, verbose_name='Tipos'),
        ),
    ]
