# Generated by Django 4.0.4 on 2022-05-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_tipoelemento_producto_tipoelemento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoelemento',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipo_elemento',
            field=models.CharField(choices=[('Accesorios', 'Accesorios'), ('Productos', 'Productos')], default='Productos', max_length=20, verbose_name='Tipo'),
        ),
    ]
