# Generated by Django 4.0.4 on 2022-05-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_remove_tipoelemento_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoElemento',
        ),
    ]
