# Generated by Django 4.0.4 on 2022-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_delete_tipoelemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='foto',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipo_elemento',
            field=models.CharField(choices=[('Accesorios', 'Accesorios'), ('Productos', 'Productos')], max_length=20, verbose_name='Tipo'),
        ),
    ]
