# Generated by Django 4.0.4 on 2022-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_alter_usuario_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipodoc',
            field=models.CharField(choices=[('C.C.', 'Cedula'), ('T.I.', 'Tarjeta'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cedula Extranjeria')], max_length=10, unique=True, verbose_name='Tipo de documento'),
        ),
    ]
