# Generated by Django 4.0.4 on 2022-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_alter_usuario_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipodoc',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
