# Generated by Django 4.0.4 on 2022-05-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_alter_usuario_tipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='porcentaje_ganancia',
            field=models.CharField(choices=[('0.1', '10%'), ('0.15', '15%'), ('0.2', '20%'), ('0.3', '30%')], max_length=10, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipodoc',
            field=models.CharField(choices=[('C.C.', 'Cedula'), ('T.I.', 'Tarjeta'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cedula Extranjeria')], max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
