# Generated by Django 4.0.4 on 2022-05-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_alter_elemento_porcentaje_ganancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
