# Generated by Django 4.0.4 on 2022-05-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0021_alter_marca_nombre_alter_servicio_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
