# Generated by Django 4.0.4 on 2022-05-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0022_alter_factura_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
