# Generated by Django 4.0.3 on 2022-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0023_alter_factura_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='foto',
            field=models.ImageField(blank=True, upload_to='elementos'),
        ),
    ]
