# Generated by Django 4.0.3 on 2022-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0025_alter_elemento_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='foto',
            field=models.ImageField(blank=True, upload_to='elementos'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='porcentaje_ganancia',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=25),
        ),
    ]
