# Generated by Django 4.0.3 on 2022-05-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0026_servicio_estado_alter_elemento_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
    ]
