# Generated by Django 4.0.4 on 2022-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0030_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipos_elemento',
            name='categoria',
        ),
        migrations.AddField(
            model_name='elemento',
            name='categoria',
            field=models.CharField(choices=[('Accesorios', 'Accesorios'), ('Productos', 'Productos')], default='Accesorios', max_length=20, verbose_name='Categoría'),
        ),
    ]
