# Generated by Django 4.0.4 on 2022-06-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0032_remove_elemento_categoria_tipos_elemento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='foto',
            field=models.ImageField(blank=True, default='carrito/casa.png', null=True, upload_to='carrito'),
        ),
    ]
