# Generated by Django 4.0.3 on 2022-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_uadministrador_usuario_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uadministrador',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador'), ('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador'), ('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=20, verbose_name='Rol'),
        ),
    ]
