# Generated by Django 4.0.4 on 2022-06-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_uadministrador_usuario_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uadministrador',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo',
        ),
    ]
