# Generated by Django 4.0.4 on 2022-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_uadministrador_codigo_remove_usuario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.EmailField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especializacion',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
