# Generated by Django 4.0.3 on 2022-06-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_uadministrador_rol_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uadministrador',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Asociada', 'Asociada'), ('Cliente', 'Cliente')], max_length=13, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol', verbose_name='Rol'),
        ),
    ]
