# Generated by Django 4.0.4 on 2022-06-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='especializacion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
