# Generated by Django 4.0.4 on 2022-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_ciudad_alter_usuario_especializacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Asociada', 'Asociada'), ('Cliente', 'Cliente')], max_length=13, null=True, verbose_name='rol'),
        ),
    ]
