# Generated by Django 4.0.4 on 2022-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Proveedor', 'Proveedor'), ('Trabajador', 'Trabajador'), ('Cliente', 'Cliente')], max_length=13, null=True, verbose_name='rol'),
        ),
    ]
