# Generated by Django 4.0.4 on 2022-06-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_cliente_proveedor_delete_uadministrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
