# Generated by Django 4.0.4 on 2022-06-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_rol'),
        ('usuarios', '0010_rename_apellidos_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
