# Generated by Django 4.1.1 on 2022-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle", name="pago", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="detalle", name="total", field=models.IntegerField(default=0),
        ),
    ]
