# Generated by Django 4.1.1 on 2022-09-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
        ("facturas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle", name="total", field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="detalleservicio",
            name="costo",
            field=models.IntegerField(default=0, verbose_name="Costo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detalleservicio",
            name="elemento",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administrador.elemento",
                verbose_name="elemento",
            ),
        ),
    ]
