# Generated by Django 4.0.4 on 2022-06-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
