# Generated by Django 4.0.4 on 2022-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Trabajador', 'Trabajador')], max_length=13, null=True, verbose_name='rol'),
        ),
    ]
